import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollWrapper from "./components/ScrollWrapper";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Nnamdi Uzoigwe | Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased 
        bg-white dark:bg-[#0d0d0d] transition-colors duration-300`}
      >
        {/* Background gradient effects */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
          {/* Top gradient blob */}
          <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
            <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
            <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
            <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
            <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
          </div>

         
        </div>

        <ThemeProvider>
          <Navbar />
          <ScrollWrapper>
          {children}
          </ScrollWrapper>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
