// import type { Metadata } from "next";
// import { Philosopher, Poppins } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "./context/ThemeContext";

// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";
// import ScrollWrapper from "./components/ScrollWrapper";



// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-poppins",
// });
// const philosopher = Philosopher({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-philosopher",
// });

// export const metadata: Metadata = {
//   title: "Nnamdi Uzoigwe | Software Developer",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {

 
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${philosopher.variable} ${poppins.variable} font-philosopher antialiased 
//         bg-white dark:bg-[#0d0d0d] transition-colors duration-300`}
//       >
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
//           {/* Top gradient blob */}
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>

         
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           <ScrollWrapper>
//           {children}
//           </ScrollWrapper>
//           <Footer />
//         </ThemeProvider>
//       </body>
//     </html>
//   )
// }


// import type { Metadata } from "next";
// import { Libre_Baskerville } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "./context/ThemeContext";

// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";
// import ScrollWrapper from "./components/ScrollWrapper";

// const libre = Libre_Baskerville({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-libre",
// });

// export const metadata: Metadata = {
//   title: "Nnamdi Uzoigwe | Software Developer",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${libre.variable} font-libre antialiased 
//         bg-white dark:bg-[#0d0d0d] transition-colors duration-300`}
//       >
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           <ScrollWrapper>{children}</ScrollWrapper>
//           <Footer />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollWrapper from "./components/ScrollWrapper";



// const open_sans = Open_Sans({
//   subsets: ["latin"],
//   variable: "--font-open_sans",
//   display: "swap",
// });

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-philosopher",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Nnamdi Uzoigwe | Software Developer",
  description: "Mobile and Website Developer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jost.variable} font-jost antialiased 
        bg-white dark:bg-[#0d0d0d] transition-colors duration-300`}
      >
        {/* Background gradient effects */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
            <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
            <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
            <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
            <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
          </div>
        </div>

        <ThemeProvider>
          <Navbar />
          <ScrollWrapper>{children}</ScrollWrapper>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}