// import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "./components/ThemeProvider";
// import Navbar from "./components/Navbar";



// const manrope = Manrope({
//   variable: "--font-manrope",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Nnamdi Uzoigwe | Software Developer",
//   description: "Generated by create next app",
// };


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={` ${manrope.variable} antialiased relative`}
//       >
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
//           {/* Top gradient blob */}
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
          
//           {/* Bottom gradient blob */}
//           <div className="absolute -bottom-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute bottom-0 left-0 w-75 h-75 bg-yellow-300/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-50 w-75 h-75 bg-red-400/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-100 w-75 h-75 bg-purple-400/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-150 w-75 h-75 bg-blue-300/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "./components/ThemeProvider";
// import Navbar from "./components/Navbar";

// const manrope = Manrope({
//   variable: "--font-manrope",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Nnamdi Uzoigwe | Software Developer",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               // Initialize theme before React loads to prevent flash
//               (function() {
//                 try {
//                   var theme = localStorage.getItem('theme');
//                   var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
//                   var isDark = false;
                  
//                   if (theme === 'dark' || (!theme && systemDark)) {
//                     isDark = true;
//                   }
                  
//                   if (isDark) {
//                     document.documentElement.classList.add('dark');
//                   } else {
//                     document.documentElement.classList.remove('dark');
//                   }
//                 } catch (e) {}
//               })();
//             `,
//           }}
//         />
//       </head>
//       <body className={`${manrope.variable} antialiased relative bg-white dark:bg-gray-900`}>
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
//           {/* Top gradient blob */}
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
          
//           {/* Bottom gradient blob */}
//           <div className="absolute -bottom-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute bottom-0 left-0 w-75 h-75 bg-yellow-300/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-50 w-75 h-75 bg-red-400/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-100 w-75 h-75 bg-purple-400/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-150 w-75 h-75 bg-blue-300/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "./components/ThemeProvider";
// import Navbar from "./components/Navbar";

// const manrope = Manrope({
//   variable: "--font-manrope",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Nnamdi Uzoigwe | Software Developer",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               // Initialize theme before React loads to prevent flash
//               (function() {
//                 try {
//                   var theme = localStorage.getItem('theme');
//                   var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
//                   var isDark = false;
                  
//                   if (theme === 'dark' || (!theme && systemDark)) {
//                     isDark = true;
//                   }
                  
//                   if (isDark) {
//                     document.documentElement.classList.add('dark');
//                   } else {
//                     document.documentElement.classList.remove('dark');
//                   }
//                 } catch (e) {}
//               })();
//             `,
//           }}
//         />
//       </head>
//       <body className={`${manrope.variable} antialiased relative bg-white dark:bg-gray-900 transition-colors duration-300`}>
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none transition-colors duration-300">
//           {/* Top gradient blob */}
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl transition-colors duration-300" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl transition-colors duration-300" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl transition-colors duration-300" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl transition-colors duration-300" />
//           </div>
          
//           {/* Bottom gradient blob */}
//           <div className="absolute -bottom-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute bottom-0 left-0 w-75 h-75 bg-yellow-300/40 dark:bg-yellow-400/20 rounded-full blur-3xl transition-colors duration-300" />
//             <div className="absolute bottom-0 left-50 w-75 h-75 bg-red-400/40 dark:bg-red-500/20 rounded-full blur-3xl transition-colors duration-300" />
//             <div className="absolute bottom-0 left-100 w-75 h-75 bg-purple-400/40 dark:bg-purple-500/20 rounded-full blur-3xl transition-colors duration-300" />
//             <div className="absolute bottom-0 left-150 w-75 h-75 bg-blue-300/40 dark:bg-blue-400/20 rounded-full blur-3xl transition-colors duration-300" />
//           </div>
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "./components/ThemeProvider";
// import Navbar from "./components/Navbar";

// const manrope = Manrope({
//   variable: "--font-manrope",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Nnamdi Uzoigwe | Software Developer",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${manrope.variable} antialiased relative
//        bg-white dark:bg-gray-950`}>
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
//           {/* Top gradient blob */}
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
          
//           {/* Bottom gradient blob */}
//           <div className="absolute -bottom-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute bottom-0 left-0 w-75 h-75 bg-yellow-300/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-50 w-75 h-75 bg-red-400/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-100 w-75 h-75 bg-purple-400/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-150 w-75 h-75 bg-blue-300/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";

import Navbar from "./components/Navbar";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nnamdi Uzoigwe | Software Developer",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${manrope.variable} antialiased 
//         bg-white dark:bg-gray-950 transition-colors duration-300`}
//       >
//         {/* Background gradient effects */}
//         <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
//           {/* Top gradient blob */}
//           <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute top-0 left-150 w-75 h-75 bg-yellow-400/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute top-0 left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>

//           {/* Bottom gradient blob */}
//           <div className="absolute -bottom-40 left-1/2 -translate-x-1/2 w-200 h-100">
//             <div className="absolute bottom-0 left-0 w-75 h-75 bg-yellow-300/40 dark:bg-yellow-400/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-50 w-75 h-75 bg-red-400/40 dark:bg-red-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-100 w-75 h-75 bg-purple-400/40 dark:bg-purple-500/20 rounded-full blur-3xl" />
//             <div className="absolute bottom-0 left-150 w-75 h-75 bg-blue-300/40 dark:bg-blue-400/20 rounded-full blur-3xl" />
//           </div>
//         </div>

//         <ThemeProvider>
//           <Navbar />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   )
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${manrope.variable}
          antialiased
          min-h-screen
          bg-white dark:bg-gray-950
          transition-colors duration-300
        `}
      >
        {/* Decorative gradients */}
        {/* <div className="fixed inset-0 -z-10 pointer-events-none">
          <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-200 h-100">
            <div className="absolute left-0 w-75 h-75 bg-blue-400/40 dark:bg-blue-400/20 blur-3xl rounded-full" />
            <div className="absolute left-50 w-75 h-75 bg-purple-500/40 dark:bg-purple-500/20 blur-3xl rounded-full" />
            <div className="absolute left-100 w-75 h-75 bg-red-500/40 dark:bg-red-500/20 blur-3xl rounded-full" />
          </div>
        </div> */}

        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
